---
- name: Install Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
  when: ansible_os_family == "Debian"

- name: Installd Fail2Ban (RedHat/CentOS)
  ansible.builtin.yum:
    name: fail2ban
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable Fail2Ban service
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

- name: Copy fail2ban configuration
  ansible.builtin.template:
    src: fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
